name: app_cotacoes
description: "Aplicativo Flutter para consulta de cotações em tempo real."

# Este projeto não será publicado no pub.dev
publish_to: 'none'

# Versão do app (nome+build)
version: 1.0.0+1

# Ambiente do SDK do Dart
environment:
  sdk: ^3.8.1

# Dependências principais do app
dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.6             # Para fazer requisições HTTP
  cupertino_icons: ^1.0.8   # Ícones no estilo iOS
  country_flags: ^2.1.0     # Exibe bandeiras a partir do código da moeda

# Dependências para desenvolvimento e testes
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0     # Regras de boas práticas

# Configurações específicas do Flutter
flutter:
  uses-material-design: true

  assets:
    - assets/imagens/logo.png
